name: Run tests

on:
  push:
  pull_request:

jobs:
  php-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        php: [8.1, 8.0]
        laravel: [9.*, 8.*]
        dependency-version: [prefer-lowest, prefer-stable]
        include:
          - laravel: 9.*
            testbench: 7.*
          - laravel: 8.*
            testbench: ^6.23

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

      # - name:               Execute tests
      #   run:                vendor/bin/phpunit

  report-status:
    needs: php-tests
    runs-on: ubuntu-latest
    steps:
      - uses: martialonline/workflow-status@v2
        id: check
      - name: Send Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ steps.check.outputs.status }}
          author_name: ${{ github.actor }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
